brainassistant/urls.py
# -*- coding: utf-8 -*-
"""django_auth_example URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

from users import views as users_views



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 别忘记在顶部引入 include 函数
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^$', users_views.index, name='index'),
	url(r'^jsmind/',include('jsmind.urls') )
]

django_auth_example/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from users import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 别忘记在顶部引入 include 函数
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^$', views.index, name='index')
]

jsmind/urls.py
from django.conf.urls import url

from . import views

app_name = 'jsmind'
urlpatterns = [
    #url(r'', views.index, name='index'),
	url(r'^owl/$', views.repoClass, name="repoclass"),
	url(r'^con/$', views.repoConn, name="repoConn"),
	url(r'^index/$', views.index, name="index"),
	url(r'^edit/$', views.edit, name="edit"),
	url(r'^viz/$', views.viz, name="viz"),
	url(r'^cal/$', views.cal, name="cal"),
	url(r'^call/$', views.call, name="call"),
	url(r'^showclass/$', views.showclass, name="showclass")
]

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^users/', views.register, name='register'),
]

templates/base.html
{% extends 'base_base.html' %}
{% block nav %}
	{% include 'nav.html' %}
{% endblock %}
 

templates/index.html
{% extends 'base.html' %}
{% block title %}欢迎页面{% endblock %}
 

templates/loginfo.html
<div class="flex-center">
    <div class="container">
        <div>
            <h1 class="logo"><a href="{% url 'index' %}">Django Auth Example</a></h1>
            {% if user.is_authenticated %}
                <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
                <button class="btn btn-default"><a href="{% url 'logout' %}?next={{ request.path }}">注销登录</a>
                </button>
                <button class="btn btn-default"><a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a>
                </button>
            {% else %}
                <p>你还没有登录，请
                    <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">登录</a>
                    </button>
                    或者
                    <button class="btn btn-default"><a href="{% url 'users:register' %}?next={{ request.path }}">注册</a>
                    </button>
                </p>
            {% endif %}
        </div>
    </div>
</div>

templates/nav.html
<nav class="navbar  navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
    <div>
        <ul class="nav navbar-nav">
            <li><a href="{% url 'jsmind:index' %}">脑图</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Echarts <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#">树图</a></li>
                    <li><a href="#">日图</a></li>
					<li><a href="#">点图</a></li>
                    <li class="divider"></li>
                    <li><a href="#">森林</a></li>
					<li><a href="#">组内(总数)</a></li>
					<li><a href="#">组内(最高最低比价)</a></li>
                    <li class="divider"></li>
                    <li><a href="#">另一个分离的链接</a></li>
                </ul>
            </li>
		</ul>

		<form class="navbar-form navbar-right" role="search">
			
			{% if user.is_authenticated %}
			<div class="form-group">
				<input type="text" class="form-control" />
				<a href="{% url 'admin:index' %}">后台数据</a>
				<a href="#">{{ user.username }}</a>
			</div> 
			<button type="submit"  class="btn btn-default">查询</button>

			<button href="{% url 'logout' %}?next={{ request.path }}"  class="btn btn-default">注销登录</button>
			<button href="{% url 'password_change' %}?next={{ request.path }}"  class="btn btn-default">修改密码</button>

			{% else %}	
			<li><a href="{% url 'login' %}?next={{ request.path }}">登录</a></li>
			或者
			<li class="btn btn-default"><a href="{% url 'users:register' %}?next={{ request.path }}">注册</a></li>
			{% endif %}
		</form>
				
		
    </div>
    </div>
</nav>